version: '3.8'

services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ".env"
    # volumes:
    #   - .:/app
    # environment:
      # - GO_ENV=development