server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[a-f0-9]{64})/'
          source: filename
      - labels:
          container_id:
      # Parse the outer JSON (Docker's format)
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - output:
          source: log